кт1
yalibina/Large_Prime_Numbers pull request #1
Opened 2024-01-17 18:55 UTC by yalibina

2024-01-20 14:52 UTC, DimaTrushin requested changes
Обрати внимание, что я комментировал ошибку только в одном месте. Если встречается подобная ошибка, то ее надо исправить во всех аналогичных местах.

Еще добавь систему сборки. Добавь main и хоть какие-то тесты, показывающие, что твой код запускается. И вообще не пиши код, которые не собирается. Потому что ты не поймешь пишешь ты компилируемый код или нет. Компилятор твой главный друг, чем больше он вовлечен в написание кода, тем лучше.

Не пиши ненужные комментарии. Если тебе нужны pre conditions на аргументы функции, проверяй их assert-ами. Так же проверяй post conditions. Была пара разумных комментариев, которые можно оставить (я пометил). Остальное -- мусор (особенно ужасен в big_gcd, я так и не понял, что там происходит).

2024-01-20 14:52 UTC, DimaTrushin commented on fast_pow.h
> +using boost_int = boost::multiprecision::cpp_int;
1) Раз ты везде используешь boost с его длинкой сделай отдельный хедер для "фасада" вокруг буста. В нем добавь все необходимые юзинги внутри Proj namespace и уже его а не бустовский хедер подтягивай себе в хедеры.
2) Может быть стоит в названии длинки скрыть, что она пришла из буста, Вдруг потом ты захочешь другую длинку использовать и название будет врать. Лучше что-то вроде using LongInt использовать и сделать longint.h соответственно.

2024-01-20 14:52 UTC, DimaTrushin commented on fast_pow.cpp
> +    while (pow > 0) {
Поставь assert на pow >= 0 потому что ты явно это подразумеваешь. Так же поставь assert на mod > 0.

2024-01-20 14:52 UTC, DimaTrushin commented on fast_pow.h
> +// maybe use built in powm?
А в бусте есть свой такой метод?

2024-01-20 14:52 UTC, DimaTrushin commented on gcd.h
> +Gcd knuth_gcd(boost_int a, boost_int b);  // computes gcd, m, n
Убьрать комментарий тут. Он не нужен, про это и так говорит сигнатура метода.

2024-01-20 14:52 UTC, DimaTrushin commented on gcd.h
> +    boost_int n;
Хорошо бы подумать о названиях номральных, но пока так пойдет с комментарием хотя бы.

2024-01-20 14:52 UTC, DimaTrushin commented on gcd.h
> +boost_int bin_gcd(boost_int a, boost_int b);
А где имплементация метода? Это не слинкуется. И выглядит так, что у тебя в проекте сильно больше файлов, чем тут. И нет системы сборки. Так не надо делать.

2024-01-20 14:52 UTC, DimaTrushin commented on gcd.cpp
> +Proj::Gcd Proj::knuth_gcd(boost_int a, boost_int b) {
Добавь ссылку на литературу и на страницу, где написан алгоритм, если ты из кнута списывала.

2024-01-20 14:52 UTC, DimaTrushin commented on fast_pow.h
> +boost_int fast_pow(boost_int base, boost_int pow, boost_int mod);
Вопрос, у буста передача данных by value тяжелая или нет? Если да, то не нужно ли принимать by const reference?

2024-01-20 14:52 UTC, DimaTrushin commented on gcd.cpp
> +    }
А встроенный в буст gcd не так работает?

2024-01-20 14:52 UTC, DimaTrushin commented on gcd.cpp
> +    return gcd(b, a % b);
Это же вызов бустовского gcd? То есть это просто обертка?

2024-01-20 14:52 UTC, DimaTrushin commented on gcd.cpp
> +Proj::boost_int Proj::calc_gcd(boost_int a, boost_int b) {
Не делай так. Не пиши явно квалификатор namespace-а. Напиши
```cpp
namespace Proj {
  // и помести все внутрь
}
```
и убери этот квалификатор везде. Это сделает имена короче и читаемее.

2024-01-20 14:52 UTC, DimaTrushin commented on gcd.cpp
> +        q = u[2] / v[2];  // rounds toward zero
К чему этот комментарий? Ты это гарантируешь? Ты это хочешь чтобы выполнялось? Что этот комментарий значит? Больше всего пробелма в том, что из-за него теперь непонятно можно доверять этому коду или он работает только если тут округление в сторону нуля.
Если тут баг, то исправь.
Если тут надо вызвать другой метод, вызови.
Если тут надо проверить assert-ом условие, проверь.
НО убери этот комментарий.

2024-01-20 14:52 UTC, DimaTrushin commented on miller_rabin.h
> +bool miller_rabin(boost_int n, int b, int k = 1);
1) Дай нормальные имена аргументам. Вот что эти аргументы значат? Почему второй и третий именно int? Не int64_t, не boost_int? Что они значат?
2) Магическая константа 1. Что она значит? Не вводи магические константы, лучше вводить constexpr константы. А чтобы их не светить пользователю, то заведи дополнительное namespace MillerRabinDetail и внутри него определяй все волшебные константы, а потом тут их используй по именам.

2024-01-20 14:52 UTC, DimaTrushin commented on miller_rabin.h
> +// k is number of iterations with different bases. gotta figure it out, for now it is unused
Тогда назови его iterations или amount_of_iterations

2024-01-20 14:52 UTC, DimaTrushin commented on miller_rabin.cpp
> +}
Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-01-20 14:52 UTC, DimaTrushin commented on miller_rabin.cpp
> +// n is odd > 3, (b,n) = 1
Если у тебя есть пререквизиты у функции, то проверяй их через assert. Это и компилятору и программисту понятно. Иначе это зря написанные строчки текста.

2024-01-20 14:52 UTC, DimaTrushin commented on miller_rabin.cpp
> +// returns 0 if n is composite, 1 if n is strong pseudoprime for the base b
Не использовать bool или int и прочие флаги со встроенными типами. Лучше делать enum class с хорошими названиями состояний, которые еще дополнительно не может конвертнуться во что-то лишнее. Напиши
```cpp
enum class TestStatus {
  Prime, Composite, Pseudoprime
};
```
и тогда возвращай TestStatus и пользователю не надо будет ломать голову что за хрень ему вернула функция.

2024-01-20 14:52 UTC, DimaTrushin commented on miller_rabin.cpp
> +bool Proj::miller_rabin(boost_int n, int b, int k) {
Код написан так, как будто у тебя есть несколько стадий, которые можно было бы выделить в подфункции, но у тебя так не сделано.

2024-01-20 14:52 UTC, DimaTrushin commented on miller_rabin.cpp
> +    boost_int test = Proj::fast_pow(boost_int(b), t, n);
Вот тут нарушение уровня абстракции. Эта строчка кода более высокоуровневая, чем весь остальной код. Такое ощущение, что код до и после должен быть завернут в какие-то содержательные методы. Это так?

2024-01-20 14:52 UTC, DimaTrushin commented on miller_rabin.cpp
> +    boost_int test = Proj::fast_pow(boost_int(b), t, n);
Не надо обращаться через Proj:: явно в рамках своего пространства имен.

2024-01-20 14:52 UTC, DimaTrushin commented on miller_rabin.cpp
> +    if (test == 1 or test == n - 1) {
Не используй or или and, используй || или &&. Так принято.

2024-01-21 14:25 UTC, yalibina commented on fast_pow.h
> +// maybe use built in powm?
да, вот тут есть
https://www.boost.org/doc/libs/1_74_0/boost/multiprecision/integer.hpp

2024-01-21 14:36 UTC, yalibina commented on gcd.cpp
> +    return gcd(b, a % b);
Бля, нет, я походу какую-то не ту версию файла закоммитила. Название функции поменяла, а внутри нет. Перепишу на нерекурсивный и поправлю название.

2024-01-21 14:39 UTC, yalibina commented on gcd.cpp
> +Proj::Gcd Proj::knuth_gcd(boost_int a, boost_int b) {
это из книги, которую ты присылал, алгоритм 1.8. https://disk.yandex.ru/i/gqm4OVfXfJXrcg

2024-01-21 14:41 UTC, yalibina commented on gcd.cpp
> +        q = u[2] / v[2];  // rounds toward zero
Я это гарантирую. В книге написано, что нужно округление вниз, и для cpp_int округление работает вниз. Типо, говорю что тут все норм сработает)) коммент уберу

2024-01-31 20:53 UTC, yalibina commented on fast_pow.h
> +boost_int fast_pow(boost_int base, boost_int pow, boost_int mod);
кажется, тяжелая. где смогла, там поставила const ref

2024-01-31 20:54 UTC, yalibina commented on miller_rabin.cpp
> +    boost_int test = Proj::fast_pow(boost_int(b), t, n);
завернула

2024-01-31 20:55 UTC, yalibina commented on gcd.cpp
> +Proj::Gcd Proj::knuth_gcd(boost_int a, boost_int b) {
или надо прям в коде оставить название книги?

2024-03-27 14:20 UTC, DimaTrushin requested changes
Добавил несколько замечаний.

2024-03-27 14:20 UTC, DimaTrushin commented on .clang-format
> +InsertNewlineAtEOF: true
ЛОЛ

2024-03-27 14:20 UTC, DimaTrushin commented on CMakeLists.txt
> +set(Boost_LIBRARY_DIR "../../../../Program Files/Boost/boost_1_84_0/libs")
Не делай платформозависимые пути для библиотек.
Посмотри вот тут в репозитории Аскара
https://github.com/fallnlove/sfastmatrixmult/pull/1/files/51369505638c0fc749ce4d0a5066bd0a6dcdfb93#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
Как он в CMakeLists.txt прописывает как cmake должен искать gtests. Можно аналогично найти и буст.
Вот тут более подробно в документации
https://cmake.org/cmake/help/latest/module/FetchContent.html
Другой вариант -- использовать пакетный менеджер conan или vcpkg или любой другой.

2024-03-27 14:20 UTC, DimaTrushin commented on README.md
Надо будет добавить инструкцию по сборке проекта и по пререквизитам (какие есть зависимости и как их установить, если их надо ставить в ручную).

2024-03-27 14:20 UTC, DimaTrushin commented on gcd.cpp
> +        a = temp;
Это можно записать так
```cpp
a = std::exchange(b, a % b);
```
и не вводить tmp. Более того, это будет эффективнее, так как у тебя не стоит std::move нигде.

2024-03-27 14:20 UTC, DimaTrushin commented on gcd.cpp
> +    return {u[0], u[1], u[2]};
Добавь как минимум std::move(u[0]), ... иначе у тебя копируются все результаты вместо мува.

2024-03-27 14:20 UTC, DimaTrushin commented on gcd.cpp
> +            u[i] = tmp;
```cpp
u[i] = std::exchange(v[i], u[i] * q - v[i]);
```
ну либо
```cpp
tmp = std::move(v[i]);
v[i] = u[i] * q - tmp;
u[i] = std::move(tmp);
```

2024-03-27 14:20 UTC, DimaTrushin commented on gcd.cpp
> +    std::array<large_int, 3> v = {0, 0, a};
1) У тебя нигде не используешься b.
2) Есть подозрение, что одно из a тут должно быть b. И тогда я бы сделал move
```cpp
std::array<large_int, 3> u = {0, 0, std::move(a)};
```
3) А еще лучше, я бы принимал аргументы a и b по ссылке, ты все равно аллоцируешь потом аж 6 новых длинных целых. Потому я бы заменил сигнатуру на
``` cpp
Gcd knuth_gcd(const large_int& a, const large_int& b)
```

2024-03-27 14:20 UTC, DimaTrushin commented on gcd.h
> +    // gcd = m * a + n * b
Это хороший комментарий.

2024-03-27 14:20 UTC, DimaTrushin commented on fast_pow.cpp
> +    return res % mod;
А разве тут надо еще одно деление с остатком? У тебя все присвоения к res идут по модулю mod или инициализация 1. Потому кажется, что нет необходимости в этом.

2024-03-27 14:20 UTC, DimaTrushin commented on miller_rabin.h
> +    large_int n;
стоит тоже написать комментарий с соотношением на эти данные.

2024-03-27 14:20 UTC, DimaTrushin commented on miller_rabin.cpp
> +// n - 1 = t * 2^a, t odd
Вот это надо перенести в описание структуры DecomposeProp в том числе

2024-03-27 14:20 UTC, DimaTrushin commented on miller_rabin.cpp
> +
А тут не надо сделать проверку, что a = 0 или a = 1 и t = 1?

2024-03-27 14:20 UTC, DimaTrushin commented on miller_rabin.cpp
> +    boost::multiprecision::uniform_int_distribution<large_int> dist(2, n - 2);
Плохая тема так делать.
1) Во-первых, у тебя генератор получается не случайным, он на каждый вызов функции заново инициализируетя и потому любой вызов этой функции будет давать один и тот же ответ на одном и том же входе.
2) Инициализировать случайным временем системы тоже плохая идея, это дает тебе не тестируемое окружение.
3) Надо сделать gen статической переменной, чтобы она инициализировалась только при первом вызове.
4) Но еще лучше сделать класс class Random, который умеет делать то, что тебе надо и не писать такие длинные методы, а именно
```cpp
class Random {
public:
  large_int uniform(const large_int& a, const large_int& b) {
    boost::multiprecision::uniform_int_distribution<large_int> dist(a, b);
    return dist(gen_);
  }
private:
  std::mt19937 gen_;
};
```
Тогда тут ты пишешь
```cpp
static Random rnd;
large_int random_number = rnd.uniform(2, n-2);
```

2024-04-20 15:54 UTC, yalibina commented on .clang-format
> +InsertNewlineAtEOF: true
я скопировала с курса плюсов просто...

2024-04-20 20:07 UTC, yalibina commented on miller_rabin.cpp
> +
> А тут не надо сделать проверку, что a = 0 или a = 1 и t = 1?

n - 1 = t * 2^a, об этих a и t речь?
Если a = 0, то n-1 нечетное, тогда n четное и оно в самом начале функции отметётся.
Если a = 1 и t = 1, то n = 3, на это тоже проверка есть в начале.
Так что не очень поняла, в чем проблема

2024-04-20 20:48 UTC, yalibina commented on CMakeLists.txt
> +set(Boost_LIBRARY_DIR "../../../../Program Files/Boost/boost_1_84_0/libs")
Лучше сделать так, а не git submodule?

2024-05-20 10:41 UTC, DimaTrushin requested changes

2024-05-20 10:41 UTC, DimaTrushin commented on CMakeLists.txt
> +gtest_discover_tests(tests)
кирпичи. Новая строка в конце каждого файла, не только в коде.

2024-05-20 10:41 UTC, DimaTrushin commented on main.cpp
> +int main() {
У тебя не отключены exception, потому надо поставить блок на них. Это делается так
```cpp
#include "Tests.h"
#include "Except.h"

int main() {
  try {
    Proj::run_all_tests();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```
В целом функция main не должна заниматься конкретной работой. Ее задача -- оркестровка на самом высоком уровне. Она лишь занимается делегированием всей работой другому коду, даже обработку исключений она делегирует.

2024-05-20 10:41 UTC, DimaTrushin commented on main.cpp
> +#include "utilities/large_type.h"
Точно все эти инклуды тут нужны?

2024-05-20 10:41 UTC, DimaTrushin commented on rsa.cpp
> +}
Настрой ide так, чтобы clang-format применялся автоматически при сохранении файла. Тогда тебе не придется париться с форматированием никогда.

2024-05-20 10:41 UTC, DimaTrushin commented on rsa.h
> +    void generate_keys(int bits_cnt);
Не помещай ничего после данных класса. Потому что как искать данные класса, если они находятся в середине класса.

2024-05-20 10:41 UTC, DimaTrushin commented on rsa.h
> +    large_int n;
Почему у класса присутствуют публичные данные? Если у тебя шифрование, это не значит, что публичные ключи надо делать публичными данными. Убрать все внутрь класса и сделать нормальный интерфейс для работы с классом.

2024-05-20 10:41 UTC, DimaTrushin commented on rsa.h
> +size_t rsa_encode(size_t e, large_int n, std::string m);
Почему эта функция не функция класса?

2024-05-20 10:41 UTC, DimaTrushin commented on rsa.cpp
> +size_t encode() {
1) Ты видимо забыла переименовать функцию в rsa_encode. Так у тебя код из хедера упадет при линковке.
2)  Порядок методов в cpp файле должен быть точно такой же как в h файле!

2024-05-20 10:41 UTC, DimaTrushin commented on utilities/fast_pow.cpp
> +    return std::move(res);
Убрать std::move в return. Его почти никогда не надо писать в return. Дело в том, что ты тем самым подавляешь nrvo и вместо него будет всегда move, что вообще говоря дороже. Чтобы nrvo затригерилось тип возвращаемого выражения должен совпадать с типом возвращаемым функцией. Функция возвращает large_int, а тип выражения после std::move будет large_int&&. Потому nrvo не сработает и будет лишь move.

2024-05-20 10:41 UTC, DimaTrushin commented on utilities/gcd.cpp
> +    return {std::move(u[0]), std::move(u[1]), std::move(u[2])};
Вот тут нормально оставить move. Но можно просто сделать return std::move(u); Должно затригериться aggregate innitialization. Если нет, то можно сделать return Gcd{u} (я сейчас наизусть не помню какие конвертации в aggregate initialization разрешены. Если ничего не сработает, то оставить так, как есть.

2024-05-20 10:41 UTC, DimaTrushin commented on utilities/prime_generator.cpp
> +    int max_trials = bit_len + 100;
Аналогично, вынеси все константы.

2024-05-20 10:41 UTC, DimaTrushin commented on utilities/reduce.cpp
> +        t >>= 1;
Ты сравнивала, есть ли прирост производительности от этого?

2024-05-20 10:41 UTC, DimaTrushin commented on utilities/reduce.cpp
> +    return {n, std::move(t), a};
А точно ты хочешь делать тут копию n и возвращать ее в этой структуре?

2024-05-20 10:41 UTC, DimaTrushin commented on test_primality/miller_rabin.h
> +TestStatus spsp_text_base(const DecomposeProp& n_reduce, const large_int& base); // spsp = strong pseudoprime
Хорошо бы в названии функций использовать глагол, чтобы понимать, что функция делает.

2024-05-20 10:41 UTC, DimaTrushin commented on test_primality/miller_rabin.cpp
> +    if (trial_division_to_max_test(n, 5000) == TestStatus::Composite) {
опять магические константы.

2024-05-20 10:41 UTC, DimaTrushin commented on test_primality/miller_rabin.cpp
> +
слишком большие пробелы.

2024-05-20 10:58 UTC, yalibina commented on utilities/gcd.cpp
> +    return {std::move(u[0]), std::move(u[1]), std::move(u[2])};
Не работает. No viable conversion в обоих случаях.

2024-05-20 11:59 UTC, yalibina commented on utilities/reduce.cpp
> +    return {n, std::move(t), a};
и правда, можно без этого.

2024-05-20 12:31 UTC, yalibina commented on utilities/reduce.cpp
> +        t >>= 1;
да, на больших числах раза в 2-3 быстрее

2024-05-21 11:04 UTC, DimaTrushin requested changes
Но рандом у тебя кривой.

2024-05-21 11:04 UTC, DimaTrushin commented on tests/sources.cmake
> +        utilities/fast_pow.cpp utilities/gcd.cpp test_primality/miller_rabin.cpp test_primality/lucas_lehmer.cpp test_primality/fermat.cpp
делай каждый файл на новой строчке единообразно.

2024-05-21 11:04 UTC, DimaTrushin commented on test_primality/trial_division_test.cpp
> +TestStatus test_trial_division_to_max(const large_int &n, large_int max) {
А почему тут второе число принимается по значению, а первое по ссылке?

2024-05-21 11:04 UTC, DimaTrushin approved these changes

2024-05-21 11:09 UTC, DimaTrushin approved these changes

2024-05-21 11:10 UTC, DimaTrushin approved these changes

2024-05-21 11:14 UTC, DimaTrushin approved these changes
Готово

2024-05-21 11:18 UTC, merged